name: Install, build and run nodejs app
 
on:
  push:
    branches: [ node-project ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Perform install, build and start commands
        run: |
            npm install
            tsc
            npm run start --if-present
